apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-crack-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-crack-service
  template:
    metadata:
      labels:
        app: image-crack-service
    spec:
      containers:
      - name: image-crack-service
        image: docker.io/library/datapush:private.guizhoutongren-v1.0.1-7ad909
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9911
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: logs-volume
          mountPath: /app/logs
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          tcpSocket:
            port: 9911
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: config-volume
        hostPath:
          path: /mnt/k3s/crackGauge/config
          type: DirectoryOrCreate
      - name: logs-volume
        hostPath:
          path: /mnt/k3s/crackGauge/logs
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: image-crack-service
  namespace: default
spec:
  selector:
    app: image-crack-service
  ports:
  - port: 9911
    targetPort: 9911
  type: ClusterIP